KEYS:
  PRIVATE_KEY:
  HELIUS_API_KEY: ''
  CIRCULAR_API_KEY: ''
BOT:
  RPC_URL: https://api.mainnet-beta.solana.com
  AUTO_RESTART: 30
  MAX_COMPUTE_TIME: 5000
  MIN_SOL_BALANCE: 0.5
  ENABLE_SIMULATION: true
  COMPUTE_UNIT_LIMIT_MULTIPLIER: 1.5
  STRATEGY: Soft
STRATEGY:
  BLIND_QUOTE:
    ENABLE: true
    BASE_MINTS:
      - MINT: So11111111111111111111111111111111111111112
        TRADE_RANGE:
          FROM: 1000000000
          TO: 10000000000
        MIN_PROFIT: 0.01
  BACKRUN:
    ENABLE: true
    DEXES:
      - Raydium
      - Orca
      - Meteora
    MIN_PROFIT: 0.005
DEX:
  PRIORITY:
    - ORCA
    - RAYDIUM
    - SERUM
  EXCLUDED:
    - ALDRIN
    - CROPPER
EXECUTION:
  MAX_CONCURRENT_TRADES: 3
  TIMEOUT_MS: 1000
  RETRY_COUNT: 3
  GAS_ADJUSTMENT: 1.5
